### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by Cheaterman** [MartinThoma/flask-httpauth-stubs#5]
Hi and thanks for merging #3 ; now that it's done, could you push a new release to PyPI please? Thanks in advance

**Comment by MartinThoma** [comment]
This is blocked by https://github.com/MartinThoma/flask-httpauth-stubs/issues/4 . Let's see, maybe over the weekend :-)

**Comment by MartinThoma** [comment]
I guess the reason was the change in authentication towards pypi.

**Comment by MartinThoma** [comment]
I've added a Github Action to automatically publish a new PyPI version once a git tag is added. Your change is now live :-)
